spring:
  application:
    name: demo-batch
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:datadb;
    username: sa
    password:
    driver-class-name: org.h2.Driver

    travail-batch:
      url: jdbc:h2:mem:batchdb;
      username: sa
      password:
      driver-class-name: org.h2.Driver

  batch:
    jdbc:
      initialize-schema: embedded
    job:
      enabled: true

logging:
  level:
    org.springframework.jdbc.datasource.init: INFO